### ISSUE TITLE
wstEth received instead of stEth

### ISSUE THREAD

**Issue by johngrantuk** [balancer/b-sdk#344] opened 2024-07-04 11:49 UTC
we have a question about balancer's order api: 
the buytoken was set to stETH, but finally our contract 'bkswap' received wstETH.
is it a bug?

ethereum hash:  0x0563ec52191cb258f6219bce0add6074ef2f4660d5c53ec504f61d4c125dea61

**Comment by brunoguerios** [comment] 2024-11-18 19:39
I'd need more context to understand this one 😅 
The new SOR doesn't even handle the stETH <> wstETH "conversion", so I'm assuming this report is regarding the old SOR?
Should we get back to whoever reported and ask for more information?
Or should we just leave it and see if anyone else complains?

**Comment by johngrantuk** [comment] 2024-12-11 16:37
> I'd need more context to understand this one 😅 The new SOR doesn't even handle the stETH <> wstETH "conversion", so I'm assuming this report is regarding the old SOR? Should we get back to whoever reported and ask for more information? Or should we just leave it and see if anyone else complains?

First step would be to confirm if this is an option on FE. If not then fine to close.

**Comment by brunoguerios** [comment] 2024-12-18 14:35
Sorry, I think I misunderstood this one. 
User shared a transaction hash and said the problem is in the batchSwap interface for Vault v2. 
Input comes from their own contract called BKSwap, so nothing related to our FE, SOR or SDK.
If we know who reported it, maybe we can connect them with SC team to answer their question on how that should behave.
Anyway, I think the issue is out of our scope, so I'll close it.

**Closed by brunoguerios** 2024-12-18 14:35 UTC
Labels: bug
